# -*- coding: utf-8 -*-
"""MLP-SKit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dSQNpc12Umq0HfAXqjvyM430h_Kg28P
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

"""بارگزاری داده و تقسیم داده ها"""

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

"""استاندارد سازی داده ها"""

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""استاندارد سازی داده ها

انواع بهینه سازها
"""

model = MLPClassifier(hidden_layer_sizes=(40, 40), activation='relu', solver='adamW', learning_rate_init=0.01, max_iter=1, warm_start=True)

"""استفاده از مدل"""

for epoch in range(50):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"Epoch {epoch + 1}, Accuracy: {accuracy:.4f}")